### ISSUE TITLE
Bug: TS types for `props.name` is wrong

### ISSUE THREAD

**Issue by janhesters** [seasonedcc/remix-forms#191]
The [example for custom error styling](https://remix-forms.seasoned.cc/examples/render-field/error-indicator) no longer works because a type mismatch of `props.name`.

```
Type 'string | number | symbol' is not assignable to type 'Key | null | undefined'.
  Type 'symbol' is not assignable to type 'Key | null | undefined'.
```

![Screenshot 2023-04-15 at 11 55 23](https://user-images.githubusercontent.com/31096420/232206877-c7315168-25e0-4e63-b00f-9153ae3c127f.png)

**Comment by danielweinmann** [comment]
Upon investigation, this has nothing to do with recent Remix upgrades :)

The example page works because it has a defined schema, and all keys in the schema are strings. But when you're defining a `renderField` for a generic form, we can't know in advance if the key will be a string, number, or symbol.

The solution is to convert the name to a string, like `key={String(name)}`.

I'm closing this, but feel free to reopen it anytime o/

**Comment by janhesters** [comment]
@danielweinmann Thanks for the clarification 🙏
