### ISSUE TITLE
Mutations are not coercing nested z.object

### ISSUE THREAD

**Issue by wladiston** [seasonedcc/remix-forms#23]
Just tried a quick example with formAction mutations but it seems like the `day`  prop from the schema below is not coercing as expacted.

```ts
const TimeSchema = z.string().regex(/\d{4}/)

 enum WeekDays {
    Sunday = 0,
    Monday = 1,
    Tuesday = 2,
    Wednesday = 3,
    Thursday = 4,
    Friday = 5,
    Saturday = 6
}

const schema = z.object({
  period: z.object({
    day: z.nativeEnum(WeekDays),
    from: TimeSchema,
    until: TimeSchema,
  }),
})
```

The form sends data correctly and `inputFromForm` function seems to be loading the data from formData correctly. I think the problem is on `getFormValues` that only loop through the first level of keys
<img width="355" alt="Screen Shot 2022-05-31 at 3 06 09 PM" src="https://user-images.githubusercontent.com/1843792/171255196-fc41e8f0-0399-40ec-b89f-8e75c8568ec4.png">

**Comment by wladiston** [comment]
https://github.com/SeasonedSoftware/remix-forms/issues/18 seems to be related

**Comment by danielweinmann** [comment]
@wladiston, I think this is not the same as #18 and we can fix this more easily :) I'll keep this issue open and work on it soon. In the meantime, in case you want to try and send a PR, I believe the problem is that [shapeInfo](https://github.com/SeasonedSoftware/remix-forms/blob/main/src/shapeInfo.ts#L18) does not know about `z.nativeEnum`.

Thank you for your contribution!

**Comment by wladiston** [comment]
Thanks mate. I’ll give it a go later on the week
