### ISSUE TITLE
Multi-step form

### ISSUE THREAD

**Issue by sgrund14** [seasonedcc/remix-forms#254]
Does this library support having a multipage form which accumulates state from step to step, but requires different validation at each step?

**Comment by danielweinmann** [comment]
Hey, @sgrund14! Merry Christmas!

We don't support multi-step forms in the sense of keeping the state in the client. That's intentional because, with Remix, we believe the best way to implement multi-step forms is with one route for each step and storing the "draft state" in the server.

Depending on your needs, you might want to store the draft state in the database (like you would store a shopping cart before creating an actual order) or in a cookie/session.

Does this make sense in your case?
